# Generated by Django 4.1.4 on 2022-12-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
