import React, { useEffect } from 'react'
import Head from 'next/head'
import Footer from './Footer'
import { useMessages } from '../contexts/MessageContext'
import 'bootstrap/dist/css/bootstrap.min.css';
import CustomAlert from './CustomAlert';
import { toast, ToastContainer } from 'react-toastify';
import MyNavbar from './MyNavbar';

export const Layout = ({children}) => {
  const {messages} = useMessages()
  useEffect(()=>{
    messages.map((message)=>toast(message.msg,{type:message.type, hideProgressBar: true, autoClose: message?.timeout || 4000,  }))
  },[messages])
  return (
        <>
            <Head>
                <title>My Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MyNavbar />
            <ToastContainer position='bottom-center' style={{maxWidth:"80%"}}/>
            <main>{children}</main>
            <Footer/>


        </>
  )
}
